MODEL:
  TYPE: dat
  NAME: swin
  DAT:
    img_size: 224
    patch_size: 4
    num_classes: 1000
    expansion: 4
    dim_stem: 96
    dims: [96, 192, 384, 768]
    depths: [2, 2, 6, 2]
    stage_spec: [[L, S], [L, S], [L, S, L, S, L, S], [L, S]]
    heads: [3, 6, 12, 24]
    window_sizes: [7, 7, 7, 7]
    use_pes: [True, True, True, True]
    dwc_pes: [False, False, False, False]
    use_dwc_mlps: [False, False, False, False]
    use_lpus: [False, False, False, False]
    use_conv_patches: False
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20

DATA:
  BATCH_SIZE: 128

SAVE_FREQ: 1